# Site settings
title: Alea Workshop
email: vincent@alea.invalid
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://workshop.alea.net" # the base hostname & protocol for your site
twitter_username: vhiribarren
github_username:  vhiribarren

# Build settings
markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge

gems:
  - jekyll-feed

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "Vincent Hiribarren"
      category: posts
      permalink: /:categories/:year/:month/:title/
