# Site settings
title: Alea Workshop
email: vincent@alea.invalid
description: >
  Software engineering workshop about personal projects, mobile apps,
  web apps, ...
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "http://workshop.alea.net" # the base hostname & protocol for your site
twitter_username: vhiribarren
github_username:  vhiribarren
linkedin_username: vhiribarren
author: Vincent Hiribarren

excerpt_separator: <!-- more -->

markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "Vincent Hiribarren"
      category: post
      permalink: /:categories/:year/:month/:title/

gems:
  - jekyll-feed


# Google services
google_analytics: UA-25235081-2
